/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.util;

import java.util.GregorianCalendar;
import javax.swing.JComboBox;

/**
 *
 * @author Milan
 */
public class PanelDateInput extends javax.swing.JPanel {

    /**
     * Creates new form PanelDateInput
     */
    public PanelDateInput() {
        initComponents();
        fillYear();
        fillMonth();
        fillDays();
    }

    public JComboBox getCmbDay() {
        return cmbDay;
    }

    public JComboBox getCmbMonth() {
        return cmbMonth;
    }

    public JComboBox getCmbYear() {
        return cmbYear;
    }

    
    public void fillYear(){
        int currentYear = new GregorianCalendar().get(GregorianCalendar.YEAR);
        for (int i = currentYear-15; i >=1900 ; i--) {
            cmbYear.addItem(i);
        }
    }
    
    private void fillMonth() {
        for(int i = 1;i<=12;i++){
            cmbMonth.addItem(i);
        }
    }
    
    private void fillDays() {
        month31();
    }
    
    public void month31(){
        cmbDay.removeAllItems();
        for (int i = 1; i <= 31; i++) {
            cmbDay.addItem(i);
        }
    }
    
    public void month30(){
        cmbDay.removeAllItems();
        for (int i = 1; i <= 30; i++) {
            cmbDay.addItem(i);
        }
    }
    
    public void month28(){
        cmbDay.removeAllItems();
        for (int i = 1; i <= 28; i++) {
            cmbDay.addItem(i);
        }
    }
    
    public void month29(){
        cmbDay.removeAllItems();
        for (int i = 1; i <= 29; i++) {
            cmbDay.addItem(i);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbDay = new javax.swing.JComboBox();
        cmbMonth = new javax.swing.JComboBox();
        cmbYear = new javax.swing.JComboBox();

        jLabel1.setText("Date of birth:");

        jLabel2.setText("day:");

        jLabel3.setText("month:");

        jLabel4.setText("year:");

        cmbMonth.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMonthItemStateChanged(evt);
            }
        });

        cmbYear.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbYearItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cmbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMonthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMonthItemStateChanged
        int month = (int) cmbMonth.getSelectedItem();
        int year = (int) cmbYear.getSelectedItem();
        switch(month){
            case 1:
            case 3:
            case 5:
            case 7:
            case 8:
            case 10:
            case 12:
                month31();
                break;
            case 4:
            case 6:
            case 9:
            case 11:
                month30();
                break;
            case 2:
                if(year%4!=0)month28();
                else if(year%100!=0) month29();
                else if(year%400!=0) month28();
                else month29();
                break;
        }
    }//GEN-LAST:event_cmbMonthItemStateChanged

    private void cmbYearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbYearItemStateChanged
        if(cmbMonth.getSelectedItem()==null) return;
        int month = (int) cmbMonth.getSelectedItem();
        int year = (int) cmbYear.getSelectedItem();
        
        if(month==2){
            if(year%4!=0)month28();
            else if(year%100!=0) month29();
            else if(year%400!=0) month28();
            else month29();
        }
    }//GEN-LAST:event_cmbYearItemStateChanged
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbDay;
    private javax.swing.JComboBox cmbMonth;
    private javax.swing.JComboBox cmbYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    

   

    
}
