/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.MenuBar;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author Brka
 */
public class FormMain extends javax.swing.JFrame {

    /** Creates new form FormMain */
    public FormMain() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelStatusBar = new javax.swing.JPanel();
        PanelMain = new javax.swing.JPanel();
        lblWelcomeUser = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuUser = new javax.swing.JMenu();
        menuItemUserAdd = new javax.swing.JMenuItem();
        menuItemUserView = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cineware");
        getContentPane().add(PanelStatusBar, java.awt.BorderLayout.PAGE_END);

        lblWelcomeUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PanelMain.add(lblWelcomeUser);

        getContentPane().add(PanelMain, java.awt.BorderLayout.CENTER);

        menuBar.setBackground(new java.awt.Color(255, 255, 255));

        menuUser.setBackground(new java.awt.Color(255, 255, 255));
        menuUser.setText("User");

        menuItemUserAdd.setBackground(new java.awt.Color(255, 255, 255));
        menuItemUserAdd.setText("Add");
        menuUser.add(menuItemUserAdd);

        menuItemUserView.setText("View");
        menuUser.add(menuItemUserView);

        menuBar.add(menuUser);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLblWelcomeUser() {
        return lblWelcomeUser;
    }

    public JMenuItem getMenuItemUserAdd() {
        return menuItemUserAdd;
    }

    public JMenuItem getMenuItemUserView() {
        return menuItemUserView;
    }

    @Override
    public MenuBar getMenuBar() {
        return super.getMenuBar(); //To change body of generated methods, choose Tools | Templates.
    }

    public JPanel getPanelMain() {
        return PanelMain;
    }

    public JPanel getPanelStatusBar() {
        return PanelStatusBar;
    }

    
    
   
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMain;
    private javax.swing.JPanel PanelStatusBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblWelcomeUser;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemUserAdd;
    private javax.swing.JMenuItem menuItemUserView;
    private javax.swing.JMenu menuUser;
    // End of variables declaration//GEN-END:variables

}
